### ISSUE TITLE
Is there any chance this plugin will see NBT writable functions?

### ISSUE THREAD

**Issue by malonnnn** [jb-aero/CHNBT#1]
I run a superhero server and I am looking to tag superhero inventory so that it's not sharable between heroes (superman shouldn't be able to to use wonder woman's lasso, for example).

However this plugin only seems to support reading NBT, not writing it. Do you think we will ever see the ability to write custom NBT tags using this plugin?

Thank you.

**Comment by jb-aero** [comment]
This was supposed to be done almost a month ago, however Windows updates destroyed my pc, and I'm currently lacking in the computing power to get it done.

**Comment by malonnnn** [comment]
Oh this is great news! I'm very happy to hear that at least writable methods are on the distant horizon.

I have another question...

Using PowerNBT I've got a workaround that does write my given NBT data and seems to work okay, however, I'm having trouble reading it correctly. It's not a problem with the plugin, it's a logic issue that I'm struggling with.

Normally I would post logic issues to the commandhelper forums, but those have been down, so I was wondering if you would help me a little.

I'm basically trying to do this:

if(itemClickedInInventory && @itemNBT[tag][heroclass] != 'specificString'){
    cancel(itemInventoryClick) 
}

All I want is that if someone tries to pickup an item in a given inventory, it cancels the action if the item doesn't belong to their hero class. I've already gotten it coded such that if a person tries to pick up an entity from the ground, the action cancels okay, so I am not complete noob, but I'm severely struggling on how to make this happen in an inventory consistently. 

I realize you don't really support stuff that's not really directly related to your plugin, so I understand if you don't have the time to help me, I just thought I would ask.

Thank you for your time!

**Comment by jb-aero** [comment]
Your logic seems fine, but I can't tell what about it you're having trouble with.

Since you have the "itemClickedInInventory" check, I take if you only want to control clicks in certain inventories. "inventorytype" from inventory_click should tell you if a certain type of inventory is open, and might reflect if the player clicks their own inventory vs the one they have open. You'll have to test that as I don't remember. If it doesn't tell you whether the top or bottom was clicked, you might be able to figure it out with "rawslot" which again, I don't remember what the exact behavior is. If this behavior is acceptable in all inventories you can get rid of that check altogether.

As for finding a string on the item, test this out on something that normally doesn't have other special data, some very basic item like a poisoned potato. Put your tag on that with PowerNBT's commands, and then use one of the [Echo](http://wiki.sk89q.com/wiki/CommandHelper/Staged/API#Echoes) functions with the read function inside to print the output somewhere so you can see the exact path to your classname.

**Comment by malonnnn** [comment]
thank you, you actually helped by the way. just your method of explaining it, cleared up my logic problem

**Comment by jb-aero** [comment]
UPDATE! Barring no new issues, I should be able to get back to this this week!

**Comment by jb-aero** [comment]
I failed to announce this, but write functions were added a few weeks ago, and ready for testing and feedback.

**Comment by malonnnn** [comment]
oh shit really?!

I will be checking this out asap!
